version: 0.2

phases:
  build:
    commands:
      - echo "Zipping Lambda code"
      - cd lambda/notes-function && zip -r ../../notes-function.zip . && cd ../..
      - cd lambda/update-notes-function && zip -r ../../update-notes-function.zip . && cd ../..
      - aws s3 cp notes-function.zip s3://$ARTIFACT_BUCKET/notes-function.zip --sse aws:kms
      - aws s3 cp update-notes-function.zip s3://$ARTIFACT_BUCKET/update-notes-function.zip --sse aws:kms
      - echo "Checking uploaded files"
      - aws s3 ls s3://$ARTIFACT_BUCKET/notes-function.zip
      - aws s3 ls s3://$ARTIFACT_BUCKET/update-notes-function.zip
      - aws s3 cp index.html s3://boris-notes-app/index.html --content-type "text/html"

artifacts:
  files:
    - NotesAppTemplate.yaml
    - index.html
    - notes-function.zip
    - update-notes-function.zip
  discard-paths: yes    
