version: 0.2

phases:
  build:
    commands:
      - echo "Zipping Lambda code"
      - cd lambda/notes-function && zip -r ../../notes-function.zip . && cd ../..
      - cd lambda/update-notes-function && zip -r ../../update-notes-function.zip . && cd ../..
      - cd lambda/insert-notes-function && zip -r ../../insert-notes-function.zip . && cd ../..
      - echo "Uploading notes-function.zip and capturing VersionId"
      #- aws s3 cp notes-function.zip s3://$ARTIFACT_BUCKET/notes-function.zip --sse aws:kms
      - export NOTES_VERSION_ID=$(aws s3api head-object --bucket $ARTIFACT_BUCKET --key notes-function.zip --query VersionId --output text)
      - echo "Uploading update-notes-function.zip and capturing VersionId"
      #- aws s3 cp update-notes-function.zip s3://$ARTIFACT_BUCKET/update-notes-function.zip --sse aws:kms
      - export UPDATE_NOTES_VERSION_ID=$(aws s3api head-object --bucket $ARTIFACT_BUCKET --key update-notes-function.zip --query VersionId --output text)
      #- echo "Checking uploaded files"
      #- aws s3 ls s3://$ARTIFACT_BUCKET/notes-function.zip
      #- aws s3 ls s3://$ARTIFACT_BUCKET/update-notes-function.zip
      - echo "Uploading insert-notes-function.zip and capturing VersionId"
      - export INSERT_NOTES_VERSION_ID=$(aws s3api head-object --bucket $ARTIFACT_BUCKET --key insert-notes-function.zip --query VersionId --output text)
      - aws s3 cp index.html s3://boris-notes-app/index.html --content-type "text/html"
      # Create a JSON file to pass the Version IDs to the CF stage
      - |
        # Use simple double quotes for JSON strings inside the Bash command
        export INNER_JSON="\"NotesZipVersion\":\"$NOTES_VERSION_ID\", \"UpdateNotesZipVersion\":\"$UPDATE_NOTES_VERSION_ID\",\"InsertNotesZipVersion\":\"$INSERT_NOTES_VERSION_ID\""
        # Create the FINAL JSON file, WRAPPED in "Parameters"
        echo "{\"Parameters\": {${INNER_JSON}}}" > version-ids.json
      # checking version-ids file
      - cat version-ids.json

artifacts:
  files:
    - NotesAppTemplate.yaml
    - index.html
    - notes-function.zip
    - update-notes-function.zip
    - insert-notes-function.zip
    - version-ids.json
  discard-paths: yes    
